title: Baron Lab Wiki
description: Wiki for members of the Baron Lab
theme: just-the-docs

url: https://baron-lab.github.io/wiki/

aux_links:
  Template Repository: https://github.com/baron-lab/wiki/
